language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - composer install
  - vendor/unb-libraries/dockworker/scripts/travis/init.sh

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: MBMIeyfwy1BxMceToWtoMNlC67s02YDI9G1waBpYQhWP2JSy3XuMAIPl2soUMlv6MNpP8Bsbz5wT9DQzhuKFlHIkyhWE6T8toT358Uw/NbRiMV2kQsuB3S0dY7PNKl6I/a57cAwozrTfgZMTLNla+i5REoQJ8p4/I3RtvrnkiZqOtk5FYYvLAh2a0pywxkzYXRO3JoJKlf0sd3ztwDhibeLXla3kKpw6E7UuNIOK5TqQIfJ4a7QG3X7VTJY9BAGglVJi6C2ZfanNmpwAGpqvNGkug/0bnMCKML+94aPTaqFWZ8rKeKFwE+bSBWttcO2dsvDt68JFkqWpUQ3M5xtfwn2D855vE4cSAD+HKm2bvsf+lYcGSlp4wEtnAELx1deRpmoQWsl7RV12BRKXcj18lrU/XIOy6ZJhjcnX1f76TRCYZzXv2qNOCwuHnC0hJr4OfuoAFaaJbJVMjUATOm/FBAQYBsaSHMU6fTmCjP9e8HKXSDTqjHlxTDmXZzQzfNwhGK+ZkUyE1HBx2kbKwX2Q1Fs3tDinTNnEWzxDL31Re5LQJ1inTM9j63r7cDZu3ES6DoOqtQyQDPbuRg0JWn605e+gK+VXN0ckqukajuB/oM0H77IssA6Uf7Y102IXAwQxAaQ/UiifAMnmzra7ABJBKqQ9FVZN41695cv+yNfEao0=
    on_start: always
    on_success: always
