services:
  preserve-lib-unb-ca:
    build: .
    env_file:
      - ./env/preserve.env
    container_name: preserve-lib-unb-ca
    ports:
      - "3091:8080"
    networks:
      - preserve.lib.unb.ca
    restart: unless-stopped
    depends_on: []
networks:
  preserve.lib.unb.ca:
    name: preserve.lib.unb.ca
