apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pywb
    tier: wayback
    uri: preserve.lib.unb.ca
  name: preserve-lib-unb-ca
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pywb
        tier: wayback
        uri: preserve.lib.unb.ca
    spec:
      containers:
        -
          env:
            -
              name: DEPLOY_ENV
              value: prod
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          name: preserve-lib-unb-ca
          ports:
            -
              containerPort: 8080
          volumeMounts:
            -
              mountPath: /app/collections
              name: pywb-persistent-storage
      priorityClassName: high-priority-services
      imagePullSecrets:
        -
          name: docker-hub-auth
      restartPolicy: Always
      volumes:
        -
          name: pywb-persistent-storage
          persistentVolumeClaim:
            claimName: preserve-lib-unb-ca
